{% set name = "acrv_datasets" %}
{% set version = "0.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74744ed61162bd55c80061c039bc3664bec601634dba08593a2c3586cbd00907

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - python >={{ python_min }}
    - pyyaml
    - requests
    - tqdm

test:
  imports:
    - acrv_datasets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/best-of-acrv/acrv-datasets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Wrapper for easy dataset access (used in Best of ACRV codebases)
  description: |
    The ACRV Datasets package is a light wrapper for generically managing
    datasets. The package supports any dataset, as long as it has a public URL.
    We emphasise that we do not own the datasets accessed through this package,
    we simply provide easy access and integration for projects like the Best of
    ACRV codebases (see https://roboticvision.org/best-of-acrv).
  doc_url: https://github.com/best-of-acrv/acrv-datasets
  dev_url: https://github.com/best-of-acrv/acrv-datasets

extra:
  recipe-maintainers:
    - btalb
